"""add assessit models

Revision ID: add_assessit_models
Revises: add_name_surname_to_user
Create Date: 2024-01-01 12:00:00.000000

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'add_assessit_models'
down_revision: Union[str, Sequence[str], None] = 'add_name_surname_to_user'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Добавляем поля в существующие таблицы
    op.add_column('assignment', sa.Column('reference_solution', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('assignment', sa.Column('reference_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('assignment', sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('assignment', sa.Column('difficulty', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('assignment', sa.Column('max_score', sa.Float(), nullable=True))

    op.add_column('question', sa.Column('formula_template', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('question', sa.Column('step_by_step_solution', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('question', sa.Column('common_mistakes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # Создаем новые таблицы для AssessIt
    op.create_table('assessmentimage',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('assignment_id', sa.Integer(), nullable=False),
        sa.Column('class_id', sa.Integer(), nullable=True),
        sa.Column('student_id', sa.Integer(), nullable=False),
        sa.Column('question_id', sa.Integer(), nullable=True),
        sa.Column('original_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('processed_image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('file_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('upload_time', sa.DateTime(), nullable=False),
        sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('processing_started', sa.DateTime(), nullable=True),
        sa.Column('processing_completed', sa.DateTime(), nullable=True),
        sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], ),
        sa.ForeignKeyConstraint(['class_id'], ['class.id'], ),
        sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
        sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('recognizedsolution',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('image_id', sa.Integer(), nullable=False),
        sa.Column('extracted_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('cleaned_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('text_confidence', sa.Float(), nullable=True),
        sa.Column('extracted_formulas_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('formulas_count', sa.Integer(), nullable=False),
        sa.Column('extracted_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('answer_confidence', sa.Float(), nullable=True),
        sa.Column('solution_steps_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('ocr_confidence', sa.Float(), nullable=True),
        sa.Column('solution_structure_confidence', sa.Float(), nullable=True),
        sa.Column('formula_confidence', sa.Float(), nullable=True),
        sa.Column('answer_match_confidence', sa.Float(), nullable=True),
        sa.Column('total_confidence', sa.Float(), nullable=True),
        sa.Column('check_level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('suggested_grade', sa.Float(), nullable=True),
        sa.Column('auto_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('processing_time_ms', sa.Integer(), nullable=True),
        sa.Column('recognized_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['image_id'], ['assessmentimage.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('assessmentresult',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('solution_id', sa.Integer(), nullable=False),
        sa.Column('teacher_id', sa.Integer(), nullable=True),
        sa.Column('teacher_verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('teacher_score', sa.Float(), nullable=True),
        sa.Column('teacher_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('corrected_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('corrected_formulas_json', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('corrected_answer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('system_score', sa.Float(), nullable=True),
        sa.Column('system_feedback', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('used_for_training', sa.Boolean(), nullable=False),
        sa.Column('training_priority', sa.Integer(), nullable=False),
        sa.Column('verified_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['solution_id'], ['recognizedsolution.id'], ),
        sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('trainingsample',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('image_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('original_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('corrected_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('handwriting_style', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('image_quality', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('used_in_training', sa.Boolean(), nullable=False),
        sa.Column('training_iteration', sa.Integer(), nullable=True),
        sa.Column('model_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('collected_at', sa.DateTime(), nullable=False),
        sa.Column('used_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('systemmetrics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('total_processed', sa.Integer(), nullable=False),
        sa.Column('level_1_count', sa.Integer(), nullable=False),
        sa.Column('level_2_count', sa.Integer(), nullable=False),
        sa.Column('level_3_count', sa.Integer(), nullable=False),
        sa.Column('avg_ocr_confidence', sa.Float(), nullable=True),
        sa.Column('avg_processing_time_ms', sa.Float(), nullable=True),
        sa.Column('error_count', sa.Integer(), nullable=False),
        sa.Column('most_common_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Создаем индексы
    op.create_index(op.f('ix_assessmentimage_assignment_id'), 'assessmentimage', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_assessmentimage_class_id'), 'assessmentimage', ['class_id'], unique=False)
    op.create_index(op.f('ix_assessmentimage_student_id'), 'assessmentimage', ['student_id'], unique=False)
    op.create_index(op.f('ix_assessmentimage_status'), 'assessmentimage', ['status'], unique=False)

    op.create_index(op.f('ix_recognizedsolution_image_id'), 'recognizedsolution', ['image_id'], unique=False)
    op.create_index(op.f('ix_recognizedsolution_check_level'), 'recognizedsolution', ['check_level'], unique=False)
    op.create_index(op.f('ix_recognizedsolution_total_confidence'), 'recognizedsolution', ['total_confidence'], unique=False)

    op.create_index(op.f('ix_assessmentresult_solution_id'), 'assessmentresult', ['solution_id'], unique=False)
    op.create_index(op.f('ix_assessmentresult_teacher_id'), 'assessmentresult', ['teacher_id'], unique=False)

    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Удаляем индексы
    op.drop_index(op.f('ix_assessmentresult_teacher_id'), table_name='assessmentresult')
    op.drop_index(op.f('ix_assessmentresult_solution_id'), table_name='assessmentresult')

    op.drop_index(op.f('ix_recognizedsolution_total_confidence'), table_name='recognizedsolution')
    op.drop_index(op.f('ix_recognizedsolution_check_level'), table_name='recognizedsolution')
    op.drop_index(op.f('ix_recognizedsolution_image_id'), table_name='recognizedsolution')

    op.drop_index(op.f('ix_assessmentimage_status'), table_name='assessmentimage')
    op.drop_index(op.f('ix_assessmentimage_student_id'), table_name='assessmentimage')
    op.drop_index(op.f('ix_assessmentimage_class_id'), table_name='assessmentimage')
    op.drop_index(op.f('ix_assessmentimage_assignment_id'), table_name='assessmentimage')

    # Удаляем таблицы
    op.drop_table('systemmetrics')
    op.drop_table('trainingsample')
    op.drop_table('assessmentresult')
    op.drop_table('recognizedsolution')
    op.drop_table('assessmentimage')

    # Удаляем поля из существующих таблиц
    op.drop_column('question', 'common_mistakes')
    op.drop_column('question', 'step_by_step_solution')
    op.drop_column('question', 'formula_template')

    op.drop_column('assignment', 'max_score')
    op.drop_column('assignment', 'difficulty')
    op.drop_column('assignment', 'subject')
    op.drop_column('assignment', 'reference_answer')
    op.drop_column('assignment', 'reference_solution')

    # ### end Alembic commands ###